<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-20T23:39:58 IST" name="Default suite" finished-at="2024-02-20T23:39:58 IST" duration-ms="87">
    <groups>
    </groups>
    <test started-at="2024-02-20T23:39:58 IST" name="Default test" finished-at="2024-02-20T23:39:58 IST" duration-ms="87">
      <class name="com.practise.selenium.v1.exampleDependent">
        <test-method signature="test()[pri:0, instance:com.practise.selenium.v1.exampleDependent@6f43c82]" started-at="2024-02-20T23:39:58 IST" name="test" finished-at="2024-02-20T23:39:58 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method signature="test3()[pri:0, instance:com.practise.selenium.v1.exampleDependent@6f43c82]" started-at="2024-02-20T23:39:58 IST" name="test3" finished-at="2024-02-20T23:39:58 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.practise.selenium.v1.exampleDependent.test3(exampleDependent.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method signature="test1()[pri:0, instance:com.practise.selenium.v1.exampleDependent@6f43c82]" started-at="2024-02-20T23:39:58 IST" name="test1" finished-at="2024-02-20T23:39:58 IST" depends-on-methods="com.practise.selenium.v1.exampleDependent.test" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test4()[pri:0, instance:com.practise.selenium.v1.exampleDependent@6f43c82]" started-at="2024-02-20T23:39:58 IST" name="test4" finished-at="2024-02-20T23:39:58 IST" depends-on-methods="com.practise.selenium.v1.exampleDependent.test3" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.practise.selenium.v1.exampleDependent.test4() on instance com.practise.selenium.v1.exampleDependent@6f43c82 depends on not successfully finished methods 
[com.practise.selenium.v1.exampleDependent.test3() on instance com.practise.selenium.v1.exampleDependent@6f43c82]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.practise.selenium.v1.exampleDependent.test4() on instance com.practise.selenium.v1.exampleDependent@6f43c82 depends on not successfully finished methods 
[com.practise.selenium.v1.exampleDependent.test3() on instance com.practise.selenium.v1.exampleDependent@6f43c82]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="test2()[pri:0, instance:com.practise.selenium.v1.exampleDependent@6f43c82]" started-at="2024-02-20T23:39:58 IST" name="test2" finished-at="2024-02-20T23:39:58 IST" depends-on-methods="com.practise.selenium.v1.exampleDependent.test, com.practise.selenium.v1.exampleDependent.test1" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.practise.selenium.v1.exampleDependent -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
